branches:
  only:
    - master

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.0
      cache:
        - bundler
        - yarn
      script: cd ios && pod spec lint