# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RN360ImageViewer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RN360ImageViewer
  pod "CTPanoramaView", "1.1"

end
